export const CREATE_CHORE_ERROR = 'CREATE_CHORE_ERROR';
export const CREATE_CHORE_SUCCESS = 'CREATE_CHORE_SUCCESS';

export const REMOVE_CHORE_ERROR = 'REMOVE_CHORE_ERROR';
export const REMOVE_CHORE_SUCCESS = 'REMOVE_CHORE_SUCCESS';

export const UNDELETE_CHORE_ERROR = 'UNDELETE_CHORE_ERROR';

export const UPDATE_CHORE_ERROR = 'UPDATE_CHORE_ERROR';
export const UPDATE_CHORE_SUCCESS = 'UPDATE_CHORE_SUCCESS';

export const FILTER_CHORES = 'FILTER_CHORES';
export const LOAD_CHORES_SUCCESS = 'LOAD_CHORES_SUCCESS';
export const UNLOAD_CHORES_SUCCESS = 'UNLOAD_CHORES_SUCCESS';
